### ISSUE TITLE
How to use multi-gpu for training

### ISSUE THREAD

**Issue by yangpanquan** [ShiQiu0419/BAAF-Net#11]
Dear sir:
Have you try to use multi-gpu for your training?
I have changed the code
os.environ['CUDA_VISIBLE_DEVICES'] = "str(FLAGS.gpu)"
to
os.environ['CUDA_VISIBLE_DEVICES'] = "0, 1"
When I  type the message "nvidia-smi" in the command line , and I found that gpu1 is still not working in fact. It still have the problem of "OOM".How should I fix this?

**Comment by ShiQiu0419** [comment]
No, I think it can only run a single GPU. You may reduce the batch size or the number of input points to fit your memory. Sorry for the inconvenience.

**Comment by yangpanquan** [comment]
Yes, it does.If I reduce the batch size or the number of input points,it can run .But I  can't reproduce the results of your experiment. Anyway, I also thank you for your patient answers.

**Comment by ShiQiu0419** [comment]
No worries. Since the pre-trained models are provided, you may take them for your evaluation need, rather than training from scratch.
