### ISSUE TITLE
The shifted neighbors and shifted neighbor feature in the BCM

### ISSUE THREAD

**Issue by yangpanquan** [ShiQiu0419/BAAF-Net#12]
Dear Sir:
    Hi , I am confused with the shifted problem in the bilateral context module.According to my memory, the RandLA-Net  is not have the shifted problem.And your code is built on RandLA-Net.Is this a basic challenge in the point cloud semantic segmentation?
what caused you to consider to solve it？I would like to take this opportunity to learn your way of thinking from you.Moreover, can you share your opinions about the problems exited in point cloud semantic segmentation.

**Comment by ShiQiu0419** [comment]
In most of related point cloud networks, the neighbors are selected based on Euclidean-distance. As for a semantic segmentation problem, following this way, you may select some points that are not in the same semantic class as your neighbors. Our motivation is to augment the selected points by learning the offsets (i.e., generate some virtual neighbors based on the selected neighbors wrt 3D Euclidean distances), making them more semantically reasonable as the neighbors.

**Comment by ShiQiu0419** [comment]
For more discussions on point cloud semantic segmentation, you may refer to this [survey paper](https://arxiv.org/pdf/1912.12033.pdf).

**Comment by yangpanquan** [comment]
Thank you very much!
