### ISSUE TITLE
The error in the code running

### ISSUE THREAD

**Issue by yangpanquan** [ShiQiu0419/BAAF-Net#4]
It is a good job, but I encountered some problems. After processing the data, there is no error, and the .ply file is also generated, but when I run BAAF-Net.py and main_s3dis.py , both files report the same error: 'process finished with exit code 139 (interrupted by signal 11: SIGSEGA)'.Besides, It can't Debug in the Pycharm. This troubles me. What should I do in this situation?

**Comment by ShiQiu0419** [comment]
Hi @yangpanquan ,

I have not encountered this issue yet. According to some online sources, it might be related to your i/o memory.

![image](https://user-images.githubusercontent.com/17152074/122660215-1b31ab80-d1c3-11eb-9ecb-3441aa84d2b1.png)

see : https://stackoverflow.com/questions/49414841/process-finished-with-exit-code-139-interrupted-by-signal-11-sigsegv

**Comment by yangpanquan** [comment]
I still can not fix it !I don't know why.If someone also encounters this kind of problem and solves it, please let me know, thank you！By the way, I understand the code by checking the code of RandLA-Net.
