### ISSUE TITLE
Bilateral Context Module ends with downsampling?

### ISSUE THREAD

**Issue by deepshwang** [ShiQiu0419/BAAF-Net#7]
Maybe it's not too significant,

but it seems like your Bilateral Context Module ends with DownSampling, whereas the figure 2. in your paper describes  BCM to end with Bilateral context block. Is it intended or is there something I'm missing?

**Comment by deepshwang** [comment]
Misread the code. My bad!

**Comment by ShiQiu0419** [comment]
Sorry for the confusion here, since we only provide a general overview of our pipeline in fig2 here.

Moreover, if you can refer to fig1 in our [supplementary ](https://openaccess.thecvf.com/content/CVPR2021/supplemental/Qiu_Semantic_Segmentation_for_CVPR_2021_supplemental.pdf), it may help you better understand the intention of our codes.

**Comment by deepshwang** [comment]
I just checked supplementary, and it seems like the fig1 in supplementary also describes bilateral context module to finish with Bilateral context block (which is the same with the fig.2 in the main paper). However, your code finishes the bilateral context module with downsampling? Am I understanding this discrepancy correctly?

**Comment by ShiQiu0419** [comment]
the gray square in supp figure1 means a "feature map" (i.e. the downsampled output of BCB), which is consistent with the codes. but in the main paper, figure 2 has some flaws, where the squre there means a block rather a "feature map".

**Comment by deepshwang** [comment]
Ah, I get it! So it DOES end with downsampling. Thanks for the quick and thorough replies... I was surprised to receive the response this fast :)

**Comment by ShiQiu0419** [comment]
Yes, it does. In general, fig2 in main paper is just to provide the readers a basic idea of our block: to process the different resolutions of point clouds. If we put such downsampling after the last block, there would be some confusion (especially for the reviewers...) 

But in supplementary, we try to put more detailed description based on our codes for a better understanding. Most people just read your main paper, obtain basic idea, and move on to another paper. 

Many thanks for your interests, and sorry again for possible confusion.
